sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 'nightly'
install: make travis-install
script: make travis-script
after_success: codeclimate-test-reporter
deploy:
- provider: pypi
  server: https://testpypi.python.org/pypi
  user: Andrew.Hawker
  password:
    secure: uzeOgGqln3Sx/c/uGn/VdRfO/rnAgFRAyiL5qCddqc9JRrh9RZC0PJbXztg4U61fW3Q1sY4CQh85VnZb2UuXKvMl4EGZMPWaWCGJUGsQ1Egu2YpvC9V7ZqwRJA4BD6FM95HRnHNEru2/JZC2b/j+GUTC5+m6zBTtsAcaHIBgiALGU/SZm+ddq93zJUlBCeESbWqZxUynB7F2qX8uc8xXYMJY5UGDWc7Yx9kHGhF9qLZ+ulxBRH/PpE3/HTm85mNPbc79fiDINW/CNrcIjGvt1JWEs9jl6tYcpzzOe1wmmgotd9mRY6O82p30U+HK6qVTNA8naPd6KwshxPEoV+AL/A1bwS9A7ZgQ5aaRomGCrPk+RwxZ+C+2FYB/377+i81Wu795r51nUlE7tdIabW2VpaIGl/nuLsloOKasnF/fiaxoovu2tdU1t2WMPTG8TBS5oHFRmxArtFs9w+NqxBEjKAlflvLeas20W7bJTXW8D176kgUcOW6lG4+W0SSs8Zosbzlpkty8K4ht3sIWsufEDB/lRmy/uuOKGhHPcwuZ2gwcUDBsOS5umWJkO+TErjRy2F5S33C42QAiwkL8Ze86cwihM0Dfm2v1Q6+pTo7b/XhDXvvqH7M/a+MWP1uGHSNpXkHwUuOAVS0914qq7432tz3nFiAxiWpvZ/zlzV5c8dw=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: false
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
- provider: pypi
  server: https://pypi.python.org/pypi
  user: Andrew.Hawker
  password:
    secure: jY9IQ+I37/c+YwtAk3d+2chRUfKW7ZF4I6DGHJwLYbuUe4b4YQbB/+yBSni2xxJxh7w2wgJnhfnT7XF05ckKdp1sD4gLlQ2Wwz1bk8oIkevmdeC9l0etZk9LLhs0Us6GAnm+K7Qn8YroBMstamFV2OcNYOd3pATFFrlEAJggR87m7SnyYpTcQJEKxQeHb1N/waFrRKy6457JNnF3ovNy6c2nggrrQIZvxyap24guUmwu3RQgxB0398CS52iP8p1O6FwQAnmn4jSb09LPAYs4WRE5Yxtfw8arzZsdWH/N6+CQ+6f3htqGZ4fjqYdjj+1CugHnwZsuT0M+n7rSmlnvbDHE0vVh2Th9AaLRwLu7i7c/Fy3eLuCPxfObhHr5UBNIkGjiFTPELoxNtGb8plwGK8TREYdcV5b1BB4mS/L8ar/zEBjZPmXHKbXQXhsBZts8hHC7RyzTEzMLRXBHjLo9WpwAnyJM4qlutd2RCkQXq/PGm9ou2e9a9WAGti8jLnMN6GQf9FtYhNAiEbo8fL6sglHt8N2fSPt9ACfoxFpVqZloamILqsJCjcPCCqeXPjtvvw1lTokLCYP/j0bU8mpQpABzhGidcs35i9uzYlZjubqofHPA6AtwxiodBZR0s90vcpolwzQ0v7bRTfDoaDqWTTkVas4ciS1ppwsnmYUfy5Y=
  distributions: sdist bdist_wheel
  skip_cleanup: true
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
notifications:
  slack:
    secure: DaTS2wAU8aP1++k1dZfksZjSWb4xsdCMA4rX1exmaxMWBoxIJzoSNqAr/Kgo80wlmMhmHGUM5TW/JLnesvT3ExeFCr0G5pORJjBr3xmSv9TL6pyshN7TBLaXNKcvTMJQuOQ0UEAdI57bNIqtdNiXHCiq/urH90tGvlVTZ38CJ13aZS6nsuRnFaMKg+oBQjsuY7JpA6kx31Xf9W+lyktcoU8Y6whFcMr7xV/j63DkqhIVpsdxNhlJNfgMIh00UBz21tIvqmBPk8WjVTmqZAzMfuGd5UkzD2AOtZsf+k0sAkcJWokVivr9WkUG1zA7Ijtsuo168w1b4sZlQpwuHSq9uXOJuwx2SUZwXsiTvS4Ew33V/0TecVlbAJM+VNcqBW4+SVKAUjYzArcIPe6l9/lY9OGwhtE9HGHijP5RBbwjLHnjFGk1GRIPpyDDGxgeGnba5DEYC4l1O8+CzibEktIa6m3lnCbSvN192/zFQsRiz5X29ol0CNIX2mGeUiHgAe1uYfPTPENruD/TLjYAaxAr4UDvLIkbSQHJMrqcwtAkwDCs18fIroj/ok5B6xTGEzPH2MPQ3a6SPR0ptENFgOu5AFRuQxVoEDIA+StkTOtxhKcgbBu5AlzdCXe28QVXw4RMhiZHYwLOoRZBvfm+/wPcH9F0YMx/Ld/WPs3dinY2bZI=
env:
  global:
  - VIRTUALENV_NO_DOWNLOAD=1
  matrix:
    secure: SLjVmaVLXbONnH4njV02LWspDxFKyXLTWbkkSt/YgD7NRfZLLlJi5oVzKdpmiJ/7LO9v67XKqL8n7Ia5vrDwz5IYpYyd3UaHkxIeasb6rvrUiXQMhBvFVuoUFpRsblZeRjayMZ6JikFNNJjZJYngqr5mxLKFzhoCaeXkJPVCpaJIGy4e79K1sKgoz+PfKVC7TjUg8fqxgUoe2rXY9qCOnygwj3gzYfPYLd4UcZxaVeuCjXHWRGxaAkY4ex7H1GtaKh1mx9zOtL0pzMjby4o8Rw3c551Azd+VZ6GdO4VcURx6D/LSkf+hPUOFfYFh1S0QZRZ3TedVwvCcvsPjaNNtJ6SfAJ1dBiFQjFjFCs9UC+DpZKr9Rt9658wUH6yw7GMc9K3Na2BDyBowaZDG0mfKEPmRYSkp1NGfIdGa7CQmI9xtABrLRIPpEmZZgR28d3mcZk8ifsrV3a075eMVPOUDUrmqzSd6DzYDsJUupsOf1MLujsHuoqNvaffrznmMO+b93hgLhb8jdnk7t6CFgh1Pd825ylqAtshghqS6De7j29ZFGlpcFg1Uw/Be3t48Fl1LG9ObY6NZ5GZizJzrUCZxztf7YiuSYqOYGcEyHBk7oe21EI+iglZMJionRK7Bhxjqm06XdwZ1YQtDFDzbEGc+1ho552PvEMOA/Z60jiQulC0=
