sudo: false
language: python
python:
- '2.7'
install: make travis-install
script: make travis-script
after_success: codeclimate-test-reporter
notifications:
  slack:
    secure: DaTS2wAU8aP1++k1dZfksZjSWb4xsdCMA4rX1exmaxMWBoxIJzoSNqAr/Kgo80wlmMhmHGUM5TW/JLnesvT3ExeFCr0G5pORJjBr3xmSv9TL6pyshN7TBLaXNKcvTMJQuOQ0UEAdI57bNIqtdNiXHCiq/urH90tGvlVTZ38CJ13aZS6nsuRnFaMKg+oBQjsuY7JpA6kx31Xf9W+lyktcoU8Y6whFcMr7xV/j63DkqhIVpsdxNhlJNfgMIh00UBz21tIvqmBPk8WjVTmqZAzMfuGd5UkzD2AOtZsf+k0sAkcJWokVivr9WkUG1zA7Ijtsuo168w1b4sZlQpwuHSq9uXOJuwx2SUZwXsiTvS4Ew33V/0TecVlbAJM+VNcqBW4+SVKAUjYzArcIPe6l9/lY9OGwhtE9HGHijP5RBbwjLHnjFGk1GRIPpyDDGxgeGnba5DEYC4l1O8+CzibEktIa6m3lnCbSvN192/zFQsRiz5X29ol0CNIX2mGeUiHgAe1uYfPTPENruD/TLjYAaxAr4UDvLIkbSQHJMrqcwtAkwDCs18fIroj/ok5B6xTGEzPH2MPQ3a6SPR0ptENFgOu5AFRuQxVoEDIA+StkTOtxhKcgbBu5AlzdCXe28QVXw4RMhiZHYwLOoRZBvfm+/wPcH9F0YMx/Ld/WPs3dinY2bZI=
env:
  global:
  - VIRTUALENV_NO_DOWNLOAD=1
